const RECIPES = {
  '매운 떡볶이': { tool: '냄비', heat: '중불', cook: 10, ingredients: ['육수', '기본 양념', '양배추', '떡', '어묵', '달걀', '대파'] },
  '로제 떡볶이': { tool: '프라이팬', heat: '약불', cook: 11, ingredients: ['베이컨·소시지', '양파', '매운 소스', '떡', '우유·크림', '브로콜리', '치즈'] },
  '치즈 떡볶이': { tool: '냄비', heat: '약불', cook: 11, ingredients: ['육수', '기본 양념', '양배추', '떡', '어묵', '옥수수', '치즈'] },
  '마라 떡볶이': { tool: '냄비', heat: '강불', cook: 13, ingredients: ['고추기름', '마라소스', '사골육수', '푸주·당면', '떡', '어묵', '숙주·청경채'] },
  '이준원 떡볶이': { tool: '프라이팬', heat: '중불', cook: 14, ingredients: ['버터·마늘', '소고기', '베이컨', '양파·버섯', '특제소스', '가래떡', '크림소스', '새우', '치즈', '반숙 달걀'] }
};
Object.assign(RECIPES, {
  '어묵꼬치': { tool:'냄비', heat:'중불', cook:7, ingredients:['육수', '어묵꼬치', '간장양념'] },
  '순대': { tool:'냄비', heat:'중불', cook:8, ingredients:['순대', '소금', '쌈장'] },
  '김말이튀김': { tool:'프라이팬', heat:'강불', cook:9, ingredients:['튀김기름', '김말이', '튀김옷'] },
  '기본 김밥': { tool:'프라이팬', heat:'약불', cook:6, ingredients:['김', '밥', '단무지·시금치', '햄·달걀'] }
});

const INGREDIENTS = [
  ['육수','🍲'],['사골육수','🥣'],['기본 양념','🌶️'],['매운 소스','🟥'],['마라소스','🌋'],['특제소스','🥫'],['고추기름','🟠'],['버터·마늘','🧈'],
  ['양배추','🥬'],['대파','🟩'],['양파','🧅'],['양파·버섯','🍄'],['브로콜리','🥦'],['숙주·청경채','🥗'],['떡','🍥'],['가래떡','🍢'],
  ['어묵','🍘'],['달걀','🥚'],['반숙 달걀','🍳'],['옥수수','🌽'],['치즈','🧀'],['우유·크림','🥛'],['크림소스','🥛'],['베이컨·소시지','🥓'],['베이컨','🥓'],['소고기','🥩'],['새우','🦐'],['푸주·당면','🍜']
];
INGREDIENTS.push(
  ['어묵꼬치','🍢'], ['간장양념','🥢'], ['순대','🫘'], ['소금','🧂'], ['쌈장','🟤'],
  ['튀김기름','🫗'], ['김말이','🥟'], ['튀김옷','🌾'], ['김','⬛'], ['밥','🍚'],
  ['단무지·시금치','🥬'], ['햄·달걀','🍳']
);

const CUSTOMERS = [
  {name:'말랑 강아지',emoji:'🐶',lines:['“따끈한 떡볶이 부탁해요!”','“치즈가 쭉 늘어나면 좋겠어요!”']},
  {name:'복슬 고양이',emoji:'🐱',lines:['“너무 늦으면 저는 낮잠을 자요.”','“오늘은 매콤한 기분이에요.”']},
  {name:'통통 돼지',emoji:'🐷',lines:['“토핑은 넉넉하게 부탁해요!”','“냄새가 정말 좋아요, 꿀꿀!”']}
];
CUSTOMERS.splice(0, CUSTOMERS.length,
  {name:'카피바라 손님',emoji:'🦫',lines:['“따끈한 떡볶이 주세요!”','“오늘도 맛있게 부탁해요.”']},
  {name:'카피바라 손님',emoji:'🦫',lines:['“치즈를 듬뿍 올려주세요!”','“배가 고파서 빨리 먹고 싶어요.”']},
  {name:'카피바라 손님',emoji:'🦫',lines:['“분식 한 접시 부탁해요!”','“매콤한 메뉴로 주세요.”']}
);

const $ = (s) => document.querySelector(s);
let state = {};
let timerId, cookId, toastId;
let orderCounter = 0;

function makeOrder(forcedCustomer){
  const names = Object.keys(RECIPES);
  const unlock = names;
  const menu = unlock[Math.floor(Math.random() * unlock.length)];
  const customer = forcedCustomer || CUSTOMERS[Math.floor(Math.random() * CUSTOMERS.length)];
  return { id:++orderCounter, menu, customer };
}
function resetState() {
  if(!state.queue.length) state.queue.push(makeOrder());
  const activeOrder = state.queue[0];
  const baseTime = Math.max(45, 70 - (state.day - 1) * 3 + (state.upgrades.pantry - 1) * 5);
  state = {...state, menu:activeOrder.menu, customer:activeOrder.customer, selectedTool:'냄비', heat:'중불', added:[], cooking:false, cookTime:0, elapsed:0, timeLeft: baseTime, maxTime:baseTime, finished:false, dayComplete:false};
  state.orderConfirmed=false; $('#confirmOrderButton').textContent='주문 확인'; $('#confirmOrderButton').classList.remove('confirmed'); renderOrder(); humanizeQueue(); styleAnimalBodies(); renderRecipe(); renderQuickGuide(); renderIngredients(); renderKitchen(); startTimer();
}
function styleAnimalBodies(){ document.querySelectorAll('.animal-human').forEach(body=>{ const emoji=body.querySelector('.animal-head')?.textContent || ''; body.classList.remove('pig','dog','cat'); body.classList.add(emoji==='🐷'?'pig':emoji==='🐶'?'dog':'cat'); }); }
function humanizeQueue(){ document.querySelectorAll('#sceneQueue .queue-person').forEach(person=>{ const head=person.querySelector('span'); if(!head || person.querySelector('.animal-human')) return; const emoji=head.textContent; head.remove(); person.insertAdjacentHTML('afterbegin',`<div class="animal-human"><span class="animal-head">${emoji}</span><i class="apron"></i><i class="leg leg-left"></i><i class="leg leg-right"></i></div>`); }); }
function confirmOrder(){ if(state.orderConfirmed) return; state.orderConfirmed=true; $('#confirmOrderButton').textContent='주문 확인 완료'; $('#confirmOrderButton').classList.add('confirmed'); toast('주문을 확인했어요! 재료를 냄비에 넣어주세요.'); }
document.addEventListener('click',(event)=>{ if(event.target.closest('#confirmOrderButton')){confirmOrder();return;} if(event.target.closest('.ingredient') && !state.orderConfirmed){event.preventDefault();event.stopImmediatePropagation();toast('손님 말풍선의 주문을 먼저 확인해주세요!');} },true);
document.addEventListener('drop',(event)=>{ if(event.target.closest('#dropZone') && !state.orderConfirmed){event.preventDefault();event.stopImmediatePropagation();toast('주문 확인 후 조리를 시작할 수 있어요.');} },true);
function startTimer(){ clearInterval(timerId); timerId=setInterval(()=>{ if(state.finished || !state.orderConfirmed) return; state.timeLeft--; renderKitchen(); if(state.timeLeft<=0){ clearInterval(timerId); toast('손님이 너무 오래 기다렸어요! 지금 완성해 주세요.'); }},1000); }
function triggerReaction(score){ const layer=$('#reactionLayer'); layer.innerHTML=''; if(score<=40){ const foods=['🍲','🌶️','🍢']; layer.innerHTML=`<span class="thrown-food">${foods[Math.floor(Math.random()*foods.length)]}</span><span class="sauce-splat">💥</span>`; } else if(score>=80){ layer.innerHTML=Array.from({length:6},(_,i)=>`<span class="kiss-mark" style="left:${12+i*15}%;top:${18+(i%2)*47}%;animation-delay:${i*.12}s">💋</span>`).join(''); } setTimeout(()=>layer.innerHTML='',2200); }
document.addEventListener('click',(event)=>{ if(!event.target.closest('#submitButton')) return; setTimeout(()=>{ const score=Number(($('#resultScore').textContent||'').replace(/\D/g,'')); if(score) triggerReaction(score); },80); });
function renderQuickGuide(){ if(!state.menu) return; const recipe=RECIPES[state.menu], iconFor=name=>INGREDIENTS.find(item=>item[0]===name)?.[1]||'•'; $('#quickMenu').textContent=`${state.menu} 조리법`; $('#quickSteps').innerHTML=recipe.ingredients.map((name,index)=>`<li class="${state.added[index]===name?'done':''}">${index+1}. ${name}</li>`).join(''); $('#quickIngredients').innerHTML=recipe.ingredients.map(name=>`<span class="${state.added.includes(name)?'used':''}">${iconFor(name)} ${name}</span>`).join(''); }
function openCookingView(){ if(!state.menu) return; const recipe=RECIPES[state.menu]; const vessel=$('#fpVessel'); vessel.classList.toggle('pan',state.selectedTool==='프라이팬'); $('#fpVesselName').textContent=state.selectedTool; $('#fpContents').textContent=state.added.length?state.added.slice(-3).join(' · '):'재료를 넣어주세요'; $('#fpCookStatus').textContent=!state.orderConfirmed?'주문 확인 후 조리 시작':state.cooking?'보글보글 끓이는 중':'재료를 넣어주세요'; $('#fpSteam').parentElement.classList.toggle('cooking',state.cooking); $('#fpCookButton').textContent=state.cooking?'불 끄기':'불 켜기'; $('#fpIngredients').innerHTML=INGREDIENTS.map(([name,icon])=>`<button class="fp-ingredient ${state.added.includes(name)?'used':''}" data-fp-ing="${name}"><span>${icon}</span>${name}</button>`).join(''); $('#fpIngredients').querySelectorAll('.fp-ingredient').forEach(button=>button.onclick=()=>{ if(!state.orderConfirmed){toast('주문 확인 후 재료를 넣을 수 있어요.');return;} addIngredient(button.dataset.fpIng); renderQuickGuide(); setTimeout(openCookingView,0); }); $('#fpCookButton').onclick=()=>{ if(!state.orderConfirmed){toast('주문 확인 후 불을 켜주세요.');return;} toggleCooking(); setTimeout(openCookingView,0); }; $('#closeCookingView').onclick=()=>$('#cookingModal').classList.add('hidden'); $('#cookingModal').classList.remove('hidden'); }
function updateFpCookGauge(){ if(!state.menu) return; const gauge=$('#fpCookGauge'); const target=Math.max(6,RECIPES[state.menu].cook-(state.upgrades.stove-1)); if(!state.cooking){gauge.classList.add('hidden');return;} const percent=Math.min(100,Math.round(state.cookTime/target*100)); gauge.classList.remove('hidden'); $('#fpGaugeBar').style.width=`${percent}%`; $('#fpGaugeText').textContent=`${percent}%`; }
setInterval(updateFpCookGauge,250);
function renderFpRecipe(){ if(!state.menu) return; const recipe=RECIPES[state.menu]; $('#fpRecipeTitle').textContent=`${state.menu} 조리법`; $('#fpRecipeSteps').innerHTML=recipe.ingredients.map((name,index)=>`<li class="${state.added[index]===name?'done':''}"><span>${index+1}</span>${name}</li>`).join(''); }
document.addEventListener('click',(event)=>{ if(event.target.closest('#pot') || event.target.closest('.tool-button')) setTimeout(()=>{openCookingView();renderFpRecipe();},0); });
document.addEventListener('click',(event)=>{ if(event.target.closest('.ingredient')) setTimeout(renderQuickGuide,0); });
document.addEventListener('click',(event)=>{ if(event.target.closest('.fp-ingredient')) setTimeout(renderFpRecipe,0); });
function startGame(){ state={coins:0,reputation:0,combo:0,day:1,served:0,dailyGoal:5,upgrades:{stove:1,pantry:1},queue:[]}; state.queue=CUSTOMERS.map(customer=>makeOrder(customer)); $('#welcomeScreen').classList.add('hidden'); $('#gameScreen').classList.remove('hidden'); resetState(); renderIntro(); $('#introModal').classList.remove('hidden'); $('#startOrdersButton').onclick=()=>$('#introModal').classList.add('hidden'); }
$('#settingsButton').onclick=()=>toast('설정은 다음 업데이트에서 추가됩니다.');
$('#creditsButton').onclick=()=>toast('리센느원이네떡볶이 · 카피바라 사장님');
function renderIntro(){ $('#introOrders').innerHTML=state.queue.map((order,index)=>`<div><span>${order.customer.emoji} ${order.customer.name}</span><b>${index+1}. ${order.menu}</b></div>`).join(''); }
function renderOrder(){ const r=RECIPES[state.menu], c=state.customer, line=c.lines[Math.floor(Math.random()*c.lines.length)]; $('#customerEmoji').textContent=c.emoji; $('#customerName').textContent=c.name; $('#customerLine').textContent=line; $('#sceneCustomerEmoji').textContent=c.emoji; $('#sceneCustomerLine').textContent=`${state.menu} 주세요!`; $('#orderMenu').textContent=state.menu; $('#toolRequest').textContent=r.tool; $('#spiciness').textContent=state.menu==='마라 떡볶이'?'얼얼하게':state.menu==='로제 떡볶이'?'순하게':'보통'; $('#extraRequest').textContent=state.menu==='치즈 떡볶이'?'치즈 듬뿍':'없음'; $('#excludeRequest').textContent='없음'; $('#queueTickets').innerHTML=state.queue.slice(1).map((order,index)=>`<div class="queue-ticket walk-in"><span>${order.customer.emoji} ${order.customer.name}</span><b>${order.menu}</b><small>${index+2}번째 주문</small></div>`).join('')||'<p class="queue-empty">다음 손님이 매장으로 들어오고 있어요…</p>'; $('#sceneQueue').innerHTML=state.queue.slice(1).map((order,index)=>`<div class="queue-person walk-in" style="animation-delay:${index*.35}s"><span>${order.customer.emoji}</span><b>${order.menu}</b></div>`).join(''); }
function renderRecipe(){ const r=RECIPES[state.menu]; const tips={ '매운 떡볶이':'떡은 중불에서 충분히 끓여주세요.', '로제 떡볶이':'우유·크림은 약불에서 부드럽게 끓여요.', '치즈 떡볶이':'치즈는 마지막에 넣어 살살 녹여요.', '마라 떡볶이':'푸주·당면을 먼저 넣고 채소는 마지막에!', '이준원 떡볶이':'새우는 살짝 익힌 뒤 마지막에 다시 넣어요.'}; $('#recipeTitle').textContent=state.menu; $('#recipeTip').textContent=tips[state.menu]; $('#recipeSteps').innerHTML=r.ingredients.map((ingredient,i)=>`<li class="${state.added[i]===ingredient?'done':''}">${ingredient}</li>`).join(''); }
function renderIngredients(){ const allowed = RECIPES[state.menu].ingredients; $('#ingredients').innerHTML=INGREDIENTS.map(([name,icon])=>`<button draggable="${!state.added.includes(name) && !state.cooking}" class="ingredient ${state.added.includes(name)?'used':''} ${allowed.includes(name)?'':'other'}" data-ing="${name}" title="${name}"><span class="ing-icon">${icon}</span>${name}</button>`).join(''); $('#ingredients').querySelectorAll('.ingredient').forEach(b=>{ b.addEventListener('click',()=>addIngredient(b.dataset.ing)); b.addEventListener('dragstart',(event)=>{event.dataTransfer.setData('text/plain',b.dataset.ing);event.dataTransfer.effectAllowed='move';}); }); }
function renderKitchen(){ const r=RECIPES[state.menu], targetCook=Math.max(6,r.cook-(state.upgrades.stove-1)); $('#ingredientCount').textContent=`${state.added.length}개 선택`; $('#sequenceList').innerHTML=state.added.length?state.added.map((x,i)=>`<li>${i+1}. ${x}</li>`).join(''):'<li class="empty">아직 넣은 재료가 없어요.</li>'; $('#potContents').textContent=state.added.length?state.added.slice(-3).join(' · '):'재료를 넣어주세요'; $('.stove-area').classList.toggle('cooking',state.cooking); $('#undoButton').disabled=state.cooking||!state.added.length; $('#cookButton').textContent=state.cooking?'조리 멈춤':'조리 시작'; $('#cookText').textContent=state.cookTime===0?'준비 중':state.cookTime < targetCook*.75?'보글보글 조리 중':'맛있게 익는 중'; $('#cookMeter').style.width=`${Math.min(100,(state.cookTime/targetCook)*100)}%`; $('#submitButton').disabled=state.added.length===0||state.finished; $('#timeText').textContent=`${state.timeLeft}초`; $('#timeMeter').style.width=`${Math.max(0,state.timeLeft/state.maxTime*100)}%`; $('#customerMood').textContent=state.timeLeft<15?'배고파요!':state.timeLeft<35?'기다리는 중':'기대 중'; $('.tool-button.active').classList.remove('active'); document.querySelector(`.tool-button[data-tool="${state.selectedTool}"]`).classList.add('active'); document.querySelectorAll('.heat-controls button').forEach(b=>b.classList.toggle('selected',b.dataset.heat===state.heat)); $('#heatHint').textContent=state.heat==='강불'?'화르륵! 빠르게 끓어요':state.heat==='약불'?'천천히 부드럽게 익어요':'중불로 보글보글!'; renderBusiness(); }
function renderBusiness(){ const stoveCost=state.upgrades.stove*25, pantryCost=state.upgrades.pantry*25; $('#day').textContent=`${state.day}일차`; $('#coins').textContent=`${state.coins * 100}원`; $('#dailyProgress').textContent=`${state.served} / ${state.dailyGoal}`; $('#dailyMeter').style.width=`${Math.min(100,state.served/state.dailyGoal*100)}%`; $('#dailyGoalText').textContent=state.served>=state.dailyGoal?'오늘 목표를 달성했어요! 내일 더 바빠질 거예요.':`손님 ${state.dailyGoal-state.served}명에게 맛있는 떡볶이를 팔아보세요!`; $('#stoveLevel').textContent=`Lv.${state.upgrades.stove} · ${stoveCost*100}원`; $('#pantryLevel').textContent=`Lv.${state.upgrades.pantry} · ${pantryCost*100}원`; $('#stoveUpgrade').disabled=state.coins<stoveCost; $('#pantryUpgrade').disabled=state.coins<pantryCost; }
function addIngredient(name){ if(state.cooking||state.finished)return; state.added.push(name); const need=RECIPES[state.menu].ingredients[state.added.length-1]; if(name===need) toast('좋아요! 다음 재료도 차례대로 넣어주세요.'); else if(RECIPES[state.menu].ingredients.includes(name)) toast('순서가 조금 달라요. 그래도 맛있게 만들 수 있어요!'); else toast('이 메뉴에는 필요 없는 재료예요. 점수가 줄 수 있어요.'); renderRecipe(); renderIngredients(); renderKitchen(); }
function startTimer(){ clearInterval(timerId); timerId=setInterval(()=>{ if(state.finished)return; state.timeLeft--; renderKitchen(); if(state.timeLeft<=0){ clearInterval(timerId); toast('손님이 너무 오래 기다렸어요! 지금 완성해 주세요.'); }},1000); }
function toggleCooking(){ if(!state.added.length){toast('먼저 재료를 넣어주세요!');return} state.cooking=!state.cooking; clearInterval(cookId); if(state.cooking){cookId=setInterval(()=>{state.cookTime+=.5;renderKitchen()},500)} renderKitchen(); }
function undo(){ if(state.cooking||!state.added.length)return; state.added.pop(); renderRecipe();renderIngredients();renderKitchen(); }
function evaluate(){ if(state.finished)return; state.finished=true; clearInterval(timerId); clearInterval(cookId); const r=RECIPES[state.menu], targetCook=Math.max(6,r.cook-(state.upgrades.stove-1)); const correctCount=state.added.filter((v,i)=>v===r.ingredients[i]).length; const exactSet=state.added.filter(x=>r.ingredients.includes(x)).length; const sequenceScore=Math.round((correctCount/r.ingredients.length)*15); const ingredientScore=Math.round((exactSet/r.ingredients.length)*25); const menuScore=exactSet>=Math.ceil(r.ingredients.length*.7)?30:Math.round(30*(exactSet/r.ingredients.length)); const heatScore=state.heat===r.heat?8:3; const cookScore=Math.max(0,Math.round(7-Math.abs(state.cookTime-targetCook)*.75)); const speedScore=Math.max(0,Math.round(10*Math.max(0,state.timeLeft)/state.maxTime)); const score=Math.min(100,menuScore+ingredientScore+sequenceScore+heatScore+cookScore+speedScore+5); showResult(score,{menuScore,ingredientScore,sequenceScore,cookScore:heatScore+cookScore,speedScore}); }
function showResult(score,parts){ let title,line,face; if(score>=90){title='완벽한 떡볶이!';line='“완벽해요! 이 집 정말 맛있네요!”';face='✨';state.combo++}else if(score>=70){title='맛있는 한 그릇!';line='“맛있어요. 다음에도 올게요.”';face='😋';state.combo++}else if(score>=50){title='조금 아쉬운 맛';line='“조금 아쉽지만 먹을 만해요.”';face='😅';state.combo=0}else if(score>=30){title='주문을 다시 확인해요';line='“주문한 것과 조금 다른데요?”';face='😕';state.combo=0}else{title='앗, 요리 실수!';line='“이건 제가 주문한 떡볶이가 아니에요!”';face='😵';state.combo=0} const coin=Math.max(2,Math.round(score/7)+(state.combo>=2?3:0)), rep=score>=70?2:score>=50?1:0; state.coins+=coin;state.reputation+=rep;state.served++;state.queue.shift();while(state.queue.length<3)state.queue.push(makeOrder());state.dayComplete=state.served>=state.dailyGoal; $('#coins').textContent=state.coins;$('#reputation').textContent=state.reputation;$('#combo').textContent=state.combo; $('#resultFace').textContent=face;$('#resultTitle').textContent=state.dayComplete?`${state.day}일차 영업 목표 달성!`:title;$('#resultScore').textContent=`${score}점`;$('#resultLine').textContent=state.dayComplete?'“오늘도 정말 수고했어요, 사장님!”':`${line}  ${coin * 100}원을 건넸어요!`;$('#rewardCoins').textContent=`${coin * 100}원`;$('#rewardRep').textContent=rep; $('#scoreBreakdown').innerHTML=`<span>메뉴·재료 <b>${parts.menuScore+parts.ingredientScore}/55</b></span><span>투입 순서 <b>${parts.sequenceScore}/15</b></span><span>불·익힘 <b>${parts.cookScore}/15</b></span><span>주문 속도 <b>${parts.speedScore+5}/15</b></span>`; $('#nextButton').innerHTML=state.dayComplete?'다음 날 영업하기 <span>→</span>':'다음 손님 받기 <span>→</span>'; $('#resultModal').classList.remove('hidden'); }
function startTimer(){ clearInterval(timerId); timerId=setInterval(()=>{ if(state.finished || state.orderConfirmed !== true) return; state.timeLeft--; renderKitchen(); if(state.timeLeft<=0){ clearInterval(timerId); toast('손님이 너무 오래 기다렸어요! 지금 완성해 주세요.'); }},1000); }
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastId);toastId=setTimeout(()=>t.classList.remove('show'),2200)}
function advanceService(){ $('#resultModal').classList.add('hidden'); if(state.dayComplete){state.day++;state.served=0;state.dailyGoal=Math.min(8,4+state.day);state.queue=[makeOrder(),makeOrder(),makeOrder()];toast(`${state.day}일차 영업을 시작합니다!`);} resetState(); }
function buyUpgrade(type){ const cost=state.upgrades[type]*25; if(state.coins<cost){toast('매출이 부족해요!');return;} state.coins-=cost;state.upgrades[type]++;renderBusiness();toast(type==='stove'?'냄비가 강화됐어요! 조리 시간이 짧아져요.':'재료 상자가 커졌어요! 주문 시간이 늘어나요.'); }

$('#startButton').addEventListener('click',startGame); $('#cookButton').addEventListener('click',toggleCooking); $('#undoButton').addEventListener('click',undo); $('#submitButton').addEventListener('click',evaluate); $('#nextButton').addEventListener('click',advanceService); $('#stoveUpgrade').addEventListener('click',()=>buyUpgrade('stove')); $('#pantryUpgrade').addEventListener('click',()=>buyUpgrade('pantry')); $('#helpButton').addEventListener('click',()=>$('#helpModal').classList.remove('hidden')); document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.add('hidden'))); $('#toggleOrder').addEventListener('click',()=>{const c=$('#ticketContent'), b=$('#toggleOrder');c.classList.toggle('hidden');b.textContent=c.classList.contains('hidden')?'+':'−'}); document.querySelectorAll('.tool-button').forEach(b=>b.addEventListener('click',()=>{if(!state.cooking){state.selectedTool=b.dataset.tool;renderKitchen()}})); document.querySelectorAll('.heat-controls button').forEach(b=>b.addEventListener('click',()=>{state.heat=b.dataset.heat;renderKitchen()})); const dropZone=$('#dropZone'); dropZone.addEventListener('dragover',(event)=>{if(!state.cooking){event.preventDefault();dropZone.classList.add('drag-over')}}); dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('drag-over')); dropZone.addEventListener('drop',(event)=>{event.preventDefault();dropZone.classList.remove('drag-over');addIngredient(event.dataTransfer.getData('text/plain'))});
